import React from 'react';

export const DOT_THUC_TAP = {
  DANG_MO: 'DANG_MO',
  DA_KHOA: 'DA_KHOA',
  KET_THUC: 'KET_THUC'
};

export const ROLE = {
  ADMIN: "ADMIN",
  BAN_CHU_NHIEM: "BAN_CHU_NHIEM",
  GIAO_VU: "GIAO_VU",
  GIANG_VIEN: "GIANG_VIEN",
  SINH_VIEN: "SINH_VIEN",
};

export const DIA_DIEM_THUC_TAP = {
  DA_XAC_NHAN: 'DA_XAC_NHAN',
  CHUA_XAC_NHAN: 'CHUA_XAC_NHAN',
  TU_CHOI: 'TU_CHOI'
}
export const DANG_KY_THUC_TAP = {
  DA_DANG_KY: 'DA_DANG_KY',
  KHONG_DU_DIEU_KIEN: 'KHONG_DU_DIEU_KIEN',
  DU_DIEU_KIEN: 'DU_DIEU_KIEN',
  CHON_GIANG_VIEN: 'CHON_GIANG_VIEN',
  GV_XAC_NHAN: 'GV_XAC_NHAN',
  GV_TU_CHOI: 'GV_TU_CHOI',
  DA_CHIA_NHOM: 'DA_CHIA_NHOM'
}



